### ISSUE TITLE
Update to v2.6.0 raises BadZipFile

### ISSUE THREAD

**Issue by fkromer** [OpenMS/pyopenms-extra#67]
On Windows , Pytho 3.8.6. an upgrade from 2.4.0 tpo 2.6.0 raised the following exception:

```
Updating dependencies
Resolving dependencies...

Package operations: 0 installs, 1 update, 0 removals

  • Updating pyopenms (2.4.0 -> 2.6.0)

  EnvCommandError

  Command D:\mvp-end-device-agent\.venv\Scripts\pip.exe install --no-deps -U file:///C:/Users/Plasmion/AppData/Local/pypoetry/Cache/artifacts/e5/19/70/ec2071b487ede5fe00136b514692e0ba8dbd27f9303bfa7f79dd9c2fa6/pyopenms-2.6.0-cp38-cp38-win_amd64.whl errored with the following return code 2, and output: 
  Processing c:\users\plasmion\appdata\local\pypoetry\cache\artifacts\e5\19\70\ec2071b487ede5fe00136b514692e0ba8dbd27f9303bfa7f79dd9c2fa6\pyopenms-2.6.0-cp38-cp38-win_amd64.whl
  ERROR: Exception:
  Traceback (most recent call last):
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\cli\base_command.py", line 228, in _main
      status = self.run(options, args)
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\cli\req_command.py", line 182, in wrapper
      return func(self, options, args)
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\commands\install.py", line 323, in run
      requirement_set = resolver.resolve(
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 183, in resolve
      discovered_reqs.extend(self._resolve_one(requirement_set, req))
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\resolution\legacy\resolver.py", line 391, in _resolve_one
      dist = abstract_dist.get_pkg_resources_distribution()
    File "D:\mvp-end-device-agent\.venv\lib\site-packages\pip\_internal\distributions\wheel.py", line 29, in get_pkg_resources_distribution
      with ZipFile(self.req.local_file_path, allowZip64=True) as z:
    File "d:\python\python386\lib\zipfile.py", line 1269, in __init__
      self._RealGetContents()
    File "d:\python\python386\lib\zipfile.py", line 1336, in _RealGetContents
      raise BadZipFile("File is not a zip file")
  zipfile.BadZipFile: File is not a zip file
```

**Comment by oliveralka** [comment]
Hi @fkromer,
where did you get the package from?

The pypi pyopenms 2.6.0 package works for me.

[pyopenms-2.6.0-cp38-cp38-win_amd64.whl](https://pypi.org/project/pyopenms/#modal-close)

I had to use numpy==1.19.3, since the 1.19.4 version throw an error due to 
```
RuntimeError: The current Numpy installation ('E:\\Programming\\Miniconda\\envs\\py38\\lib\\site-packages\\numpy\\__init__.py') fails to pass a sanity check due to a bug in the windows runtime. See this issue for more information: https://tinyurl.com/y3dm3h86
```
